services:
  db:
    image: postgres:15.3
    container_name: postgres
#    ports:
#      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: host

  redis:
    image: redis:latest
    restart: always
#    ports:
#      - "6379:6379"
    volumes:
      - redis:/root/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=SecretRedis123!!
      - REDIS_PORT=6379
    network_mode: host

#  web:
#    image: araziz/apps:certificate-generator
#    ports:
#      - 3000:3000
#    volumes:
#      - uploaded_files:/app/uploads
#      - ./google-creds.json:/app/google-creds.json
#    environment:
#      - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
#      - REDIS_URL=redis:6379
#      - DATABASE_URL=${DATABASE_URL}
#      - DB_HOST=${DB_HOST}
#      - DB_USER=${DB_USER}
#      - DB_PASSWORD=${DB_PASSWORD}
#      - DB_NAME=${DB_NAME}
#      - AUTH_SECRET=${AUTH_SECRET}
#      - AUTH_TRUST_HOST=https://certificate-ssdmpolri.my.id
#      - AUTH_URL=https://certificate-ssdmpolri.my.id/api/auth
#      - SECRET=${SECRET}
#      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
#      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
#      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
#      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
#      - EMAIL_FROM=${EMAIL_FROM}
#      - RESEND_API_KEY=${RESEND_API_KEY}
#      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
#      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
#      - ADMIN_EMAILS=faradilla393@gmail.com,anisrahmatulaziz@gmail.com
#    depends_on:
#      - db
volumes:
  postgres-data:
  uploaded_files:
  redis:
    driver: local
