version: '3.9'

services:
  #  gotenberg:
  #    image: gotenberg/gotenberg:8
  #    command:
  #      - 'gotenberg'
  #      - '--api-enable-basic-auth'
  #      - '--chromium-disable-javascript=true'
  #      - '--chromium-allow-list=file:///tmp/.*'
  #      - '--log-level=warn'
  #      - '--log-format=text'
  #    ports:
  #      - 3100:3000
  #    environment:
  #      - GOTENBERG_API_BASIC_AUTH_USERNAME=convert
  #      - GOTENBERG_API_BASIC_AUTH_PASSWORD=Convert123!!

  web:
    image: araziz/apps:certificate-generator
    ports:
      - 3000:3000
    volumes:
      - uploaded_files:/app/uploads
    environment:
      - NEXT_PUBLIC_HOST=${NEXT_PUBLIC_HOST}
      - REDIS_URL=${REDIS_URL}
      - POSTGRE_URL=${POSTGRE_URL}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AUTH_SECRET=${AUTH_SECRET}
      - SECRET=${SECRET}
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
    depends_on:
      - db
  db:
    image: postgres:15.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data:
  uploaded_files:
